#Preprocessing




> Parthiv Desai

> CPSC - 483 - 03 





















# Importing the libraries

In [ ]:
import numpy as np  #Numpy is widely used library for handling number
import matplotlib.pyplot as plt #Provides a library for data visualization for plotting graphs
import pandas as pd  #Used for data manipulation

# Importing the dataset

In [ ]:
dataset = pd.read_csv("/content/drive/MyDrive/Data.csv") #Pull the Data.csv file from CSV into a variable.
x_values = dataset.iloc[:,:-1].values #Indexing all the values till the last row.
y_values = dataset.iloc[:,-1].values #Indexing all the values till the last column.


In [ ]:
print(x_values) #Printing all the X values

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y_values) #Printing all the y values

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# Taking care of missing data

In [ ]:
from sklearn.impute import SimpleImputer #SimpleImputer is used for imputing missing values
imputer = SimpleImputer(missing_values=np.nan, strategy = 'median') #This implies replacing missing values with different strategies like mean and median. 
imputer.fit(x_values[:,1:3]) #The : refers to selecting every row in the data set, 1:3 indicates selecting first 3 columns. 
x_values[:,1:3] = imputer.transform(x_values[:,1:3])

In [ ]:
print(x_values)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Encoding the Categorical data
## Encoding independent variable

In [ ]:
from sklearn.compose import ColumnTransformer #Used for applying transformers to the columns. 
from sklearn.preprocessing import OneHotEncoder #OneHotEncoder is used to create binary column for every value and return a sparse matrix.
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough' ) #Creating  a column Transformer.  
x_values = np.array(ct.fit_transform(x_values)) #Next, we fit and transform the created column transformaer to a label encode.

In [ ]:
print(x_values)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 61000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.0 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


# Encoding Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder #Encode target values and the variable y is the target value.
le = LabelEncoder() #This function is helpful for encoding labels to specific classes.
y_values = le.fit_transform(y_values) #Indicating a use of a combination of fit and transform method.

In [ ]:
print(y_values)

[0 1 0 0 1 1 0 1 0 1]


# Splitting the dataset into Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split #Splitting data into random train and test basically converting the data into a one-liner
x_train, x_test, y_train,y_test = train_test_split(x_values,y_values,test_size = 0.2, random_state= 1) #Assign the test size at 0.2 so 80% of the data will be used for training and 20% will be used for testing.Random state is used for deciding the splitting of a given data by initializing the internal random number 

In [ ]:
print(x_train) #Printing all the independent variables that will be used for training purposes for x.

[[1.0 0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 1.0 0.0 40.0 61000.0]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(x_test) #Printing the x_test that shows 20% that will be used for testing the accuracy.

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train) #Printing the dependent variable

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test) #This prints the values that will be used for testing the accuracy.

[0 1]


# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() #This function helps standardize features by removing the mean and scaling to unit variance to assign a standard format to the data values.
x_train[:,3:] = sc.fit_transform(x_train[:,3:]) #Use a combination of fit and transform method for training.
x_test[:,3:] = sc.transform(x_test[:,3:]) #testing the x values for unbiased evaluation and it only uses transform method because we cannot use fit method.


In [ ]:
print(x_train) #Printing the x_train

[[1.0 0.0 0.0 1.2909944487358056 -0.28942984211696865 -1.0430254692900243]
 [1.0 0.0 1.0 -0.7745966692414834 0.0 -0.2767210428728636]
 [0.0 1.0 0.0 -0.7745966692414834 0.5788596842339373 0.659873256081444]
 [1.0 0.0 0.0 1.2909944487358056 -0.28942984211696865 -0.2767210428728636]
 [1.0 0.0 0.0 1.2909944487358056 -1.8812939737602963 -1.383605214364318]
 [0.0 1.0 0.0 -0.7745966692414834 1.1577193684678746 1.2558878099614579]
 [1.0 0.0 1.0 -0.7745966692414834 1.4471492105848434 1.5964675550357514]
 [0.0 1.0 0.0 -0.7745966692414834 -0.7235746052924217 -0.5321558516785838]]


In [ ]:
print(x_test) #Printing the x_test

[[1.0 0.0 1.0 -0.7745966692414834 -1.4471492105848434 -0.8727355967528775]
 [0.0 1.0 0.0 -0.7745966692414834 -0.434144763175453 0.2341485747385769]]


In [ ]:
print(x_values) #Printing the x values

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 61000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.0 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]
