>Parthiv Desai

>CPCSC 483 - 03

>Regression and Classification Project

In [7]:
import numpy as np  #Numpy is widely used library for handling number
import matplotlib.pyplot as plt #Provides a library for data visualization for plotting graphs
import pandas as pd  #Used for data manipulation

#Simple Regression

In [8]:
dataset = pd.read_csv("/content/drive/MyDrive/Data_regression_project.csv") #Pull the .csv file from CSV into a variable.
x_sim = dataset.iloc[:,:-1].values
y_sim = dataset.iloc[:, -1].values

In [9]:
from sklearn.model_selection import train_test_split #Splitting data into random train and test basically converting the data into a one-liner
X_train,X_test,y_train,y_test = train_test_split(x_sim,y_sim,test_size = 0.2,random_state= 0) #Assign the test size at 0.3 so 70% of the data will be used for training and 30% will be used for testing.Random state is used for deciding the splitting of a given data by initializing the internal random number 

In [10]:
from sklearn.linear_model import LinearRegression #Import the linear regression packages for the purposes of Linear approximations.
regressor = LinearRegression() #This function enables fitting linear models to the data frames
regressor.fit(X_train, y_train) #The .fit() method helps implementing fitting line to the data.

LinearRegression()

In [11]:
y_pred = regressor.predict(X_test) # Storing the predicted values for all the values of x_test.

In [12]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(f"R-squared:",r2)

R-squared: 0.9325315554761303


#Multi Regression

In [13]:
dataset = pd.read_csv("/content/drive/MyDrive/Data_regression_project.csv") #Pull the Data.csv file from CSV into a variable.
X_multi = dataset.iloc[:,:-1].values
y_multi = dataset.iloc[:, -1].values

In [14]:
from sklearn.model_selection import train_test_split #Splitting data into random train and test basically converting the data into a one-liner
X_train,X_test,y_train,y_test = train_test_split(x_sim,y_sim,test_size = 0.2,random_state= 0) #Assign the test size at 0.3 so 70% of the data will be used for training and 30% will be used for testing.Random state is used for deciding the splitting of a given data by initializing the internal random number 

In [15]:
from sklearn.linear_model import LinearRegression #Import the linear regression packages for the purposes of Linear approximations.
regressor = LinearRegression() #This function enables fitting linear models to the data frames
regressor.fit(X_train, y_train) #The .fit() method helps implementing fitting line to the data.

LinearRegression()

In [16]:
y_pred = regressor.predict(X_test) # Storing the predicted values for all the values of x_test.
np.set_printoptions(precision = 3) # set_printoptions function is used for setting the direction of floating point numbers and array can be displayed.
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)) #Printing the concatenated form after reshaping the arrays of y_test and y_pred.

[[431.428 431.23 ]
 [458.561 460.01 ]
 [462.753 461.14 ]
 ...
 [469.518 473.26 ]
 [442.418 438.   ]
 [461.883 463.28 ]]


In [17]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(f"R-squared:",r2)

R-squared: 0.9325315554761303


#Polynomial Regresion

In [18]:
datasetp = pd.read_csv("/content/drive/MyDrive/Data_regression_project.csv") #Pull the Data.csv file from CSV into a variable.
xpoly= datasetp.iloc[:,:-1].values  
ypoly= datasetp.iloc[:,-1].values  

In [19]:
from sklearn.model_selection import train_test_split #Splitting data into random train and test basically converting the data into a one-liner
X_train,X_test,y_train,y_test = train_test_split(xpoly,ypoly,test_size = 0.2,random_state= 42) #Assign the test size at 0.3 so 70% of the data will be used for training and 30% will be used for testing.Random state is used for deciding the splitting of a given data by initializing the internal random number 

In [20]:
from sklearn.preprocessing import PolynomialFeatures #Libraries needed for using differnet polynomial combinations that depends on the degree specified.
poly_reg = PolynomialFeatures(degree = 6) #Assigning a degree of 3, so restricting the number of features to 4.
x_poly = poly_reg.fit_transform(X_train) #Fitting the data and than transformation the data of x.
lin_reg_2 = LinearRegression() #Performing linear regression on the polynomial combination.
lin_reg_2.fit(x_poly,y_train) #Fitting the lin_reg_2 using x_poly.
X_test_poly = poly_reg.transform(X_test)

y_pred = lin_reg_2.predict(X_test_poly)

In [21]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(f"R-squared:",r2)

R-squared: 0.9455227064108829


#Support Vector Regression

In [22]:
datasetsvr = pd.read_csv("/content/drive/MyDrive/Data_regression_project.csv") #Pull the Position_Salaries_poly-1.csv file from CSV into a variable.
x_svr = datasetsvr.iloc[:,:-1].values #Indexing all the values till the last row.
y_svr = datasetsvr.iloc[:, -1].values #Indexing all the values till the last column.

In [23]:
from sklearn.model_selection import train_test_split #Splitting data into random train and test basically converting the data into a one-liner
X_train,X_test,y_train,y_test = train_test_split(x_svr,y_svr,test_size = 0.2,random_state= 0) #Assign the test size at 0.3 so 70% of the data will be used for training and 30% will be used for testing.Random state is used for deciding the splitting of a given data by initializing the internal random number 

In [24]:
from sklearn.svm import SVR #Importing the SVR model.
regressor = SVR() #Creating a default model object.
regressor.fit(X_train,y_train)#Fitting the model on the dataset.

SVR()

In [25]:
y_pred = regressor.predict(X_test) #Predicting the new result

In [26]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(f"R-squared:",r2)

R-squared: 0.3818211045129358


#Decision Tree Regression

In [27]:
dataset = pd.read_csv("/content/drive/MyDrive/Data_regression_project.csv") #Pull the Position_Salaries_poly-1.csv file from CSV into a variable.
x_dtr = dataset.iloc[:,:-1].values #Indexing all the values till the specific row.
y_dtr = dataset.iloc[:,-1].values #Indexing all the values till the specific column.

In [28]:
from sklearn.model_selection import train_test_split #Splitting data into random train and test basically converting the data into a one-liner
X_train,X_test,y_train,y_test = train_test_split(x_dtr,y_dtr,test_size = 0.2,random_state= 1) #Assign the test size at 0.3 so 70% of the data will be used for training and 30% will be used for testing.Random state is used for deciding the splitting of a given data by initializing the internal random number 

In [29]:
from sklearn.tree import DecisionTreeRegressor #Importing Decision Tree regression regressor.
regressor = DecisionTreeRegressor(random_state = 0) #Creating a Decision Tree Regressor object with a random state at 0.  
regressor.fit(X_train,y_train) #Fitting the regressor with x_values and y from the given dataset.

DecisionTreeRegressor(random_state=0)

In [30]:
y_pred = regressor.predict(X_test)#Predicing a new value to test the output by assigning a value of 3200
print(y_pred)  #Printing the predicted value y_pred.

[459.65 462.26 436.03 ... 477.18 432.78 468.23]


In [31]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(f"R-squared:",r2)

R-squared: 0.9342783714449767


#Random Forest Regression

In [32]:
dataset_rfr = pd.read_csv("/content/drive/MyDrive/Data_regression_project.csv") #Pull the Position_Salaries_poly-1.csv file from CSV into a variable.
x_rfr = dataset_rfr.iloc[:,:-1].values #Indexing all the values till a specific row.
y_rfr = dataset_rfr.iloc[:,-1].values #Indexing all the values till a specific column.

In [33]:
print(x_rfr) #Printing x_values data value. 

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [34]:
from sklearn.model_selection import train_test_split #Splitting data into random train and test basically converting the data into a one-liner
X_train,X_test,y_train,y_test = train_test_split(x_rfr,y_rfr,test_size = 0.2,random_state= 0) #Assign the test size at 0.3 so 70% of the data will be used for training and 30% will be used for testing.Random state is used for deciding the splitting of a given data by initializing the internal random number 

In [35]:
from sklearn.ensemble import RandomForestRegressor #Importing the regressor for fitting RFR to the given dataset/
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0) #Create regressor object that fits an amount of decision trees on multiple sub-samples in the dataset.n_estimaters is used to assign the nummber of trees in the forest. random_state is responsible for controlling the randomness.  
regressor.fit(X_train,y_train) #Fitting  the regression with x_values and y data in the given dataset.

RandomForestRegressor(random_state=0)

In [36]:
y_pred = regressor.predict(X_test)  #testing the predictedoutput by changing values.

In [37]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(f"R-squared:",r2)

R-squared: 0.9651134932556499


#Logistics Regression

In [38]:
dataset_lr = pd.read_csv("/content/drive/MyDrive/Data_classification_copy.csv") #Pull the Position_Salaries_poly-1.csv file from CSV into a variable.
x_lr = dataset_lr[['Sample code number', 'Clump Thickness']]
y_lr = dataset_lr['Class']

In [39]:
y_lr = np.ravel(y_lr)

In [40]:
from sklearn.model_selection import train_test_split #Importing train_test_split that is a method to split the specified dataset into training set and testing set.
X_train,X_test,y_train,y_test=train_test_split(x_lr,y_lr,test_size = 0.2, random_state = 0) #Four subsets are returned. x_values is the data matrix. y is the target variable. X_train and y_train are used for training the model. X_test and y_test are used to evaluate the performance of the given model.

In [41]:
from sklearn.preprocessing import StandardScaler #Importing Standard scaler libraries
sc = StandardScaler() #Creating a standardScaler object that can be used for transforming the given data. StandardScalar is used for rescaling the features for implementing standard normal distribution. 
X_train=sc.fit_transform(X_train) #Implement the fit_transform method to the X_train to fit the scaler on the training data
X_test=sc.transform(X_test) #When implementing, it results in each feature with a mean of 0 and a standard deviation of 1, therefore resulting in better performnace

In [42]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression() #Use the Radial basis function kernel. 
classifier.fit(X_train,y_train) #Fit method helps in training the classifier on the given training data.

LogisticRegression()

In [43]:
y_pred = classifier.predict(X_test)#Predicting the X_test dataset which is a 2-D array containing independent variables. 

In [44]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) #The concatenation helps to concatenate the previously predicted values and actuaal values in the same column and in a single array.

[[2 2]
 [2 2]
 [2 4]
 [2 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 4]
 [4 4]
 [2 2]
 [2 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 4]
 [2 2]
 [2 4]
 [4 4]
 [4 4]
 [2 2]
 [4 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 4]
 [2 2]
 [2 2]
 [2 2]
 [2 4]
 [2 2]
 [2 2]
 [2 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 4]
 [2 2]]


In [45]:
from sklearn.metrics import confusion_matrix,accuracy_score #Importing the confusing matrix and accuracy_score libraries
cm = confusion_matrix(y_test,y_pred) #The confusion matrix forms a table that summarizes the function and performance of the given algorithm of the test values. It successfully depicts true positive,negative and false positive, negative predictions.
print(cm) #Printing confusion matrix
accuracy = accuracy_score(y_test, y_pred) #Accuracy_score function is used for computing the accuracy of the previous classifier by getting accurate predictions and results are only the true positive and true negative.
print("Accuracy:", accuracy)

[[84  3]
 [15 35]]
Accuracy: 0.8686131386861314


#Kernel Classification

In [46]:
dataset_kernel = pd.read_csv("/content/drive/MyDrive/Data_classification_copy.csv") #Pull the Social_Network_Ads.csv file from CSV into a variable.
x_values = dataset_kernel.iloc[:, :-1].values
y = dataset_kernel.iloc[:, -1].values #Indexing all the values till the last column.

In [47]:
from sklearn.model_selection import train_test_split #Importing train_test_split that is a method to split the specified dataset into training set and testing set.
X_train,X_test,y_train,y_test=train_test_split(x_values,y,test_size = 0.20, random_state = 0) #Four subsets are returned. x_values is the data matrix. y is the target variable. X_train and y_train are used for training the model. X_test and y_test are used to evaluate the performance of the given model.

In [48]:
from sklearn.preprocessing import StandardScaler #Importing Standard scaler libraries
sc = StandardScaler() #Creating a standardScaler object that can be used for transforming the given data. StandardScalar is used for rescaling the features for implementing standard normal distribution. 
X_train=sc.fit_transform(X_train) #Implement the fit_transform method to the X_train to fit the scaler on the training data
X_test=sc.transform(X_test) #When implementing, it results in each feature with a mean of 0 and a standard deviation of 1, therefore resulting in better performnace

In [49]:
from sklearn.svm import SVC #Importing SVC class from svm classifier.
classifier = SVC(kernel = 'linear', random_state = 0) #Use the Radial basis function kernel. 
classifier.fit(X_train,y_train) #Fit method helps in training the classifier on the given training data.

SVC(kernel='linear', random_state=0)

In [50]:
y_pred = classifier.predict(X_test)#Predicting the X_test dataset which is a 2-D array containing independent variables. 

In [51]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) #The concatenation helps to concatenate the previously predicted values and actuaal values in the same column and in a single array.

[[2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 4]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]]


In [52]:
from sklearn.metrics import confusion_matrix,accuracy_score #Importing the confusing matrix and accuracy_score libraries
cm = confusion_matrix(y_test,y_pred) #The confusion matrix forms a table that summarizes the function and performance of the given algorithm of the test values. It successfully depicts true positive,negative and false positive, negative predictions.
print(cm) #Printing confusion matrix
accuracy = accuracy_score(y_test, y_pred) #Accuracy_score function is used for computing the accuracy of the previous classifier by getting accurate predictions and results are only the true positive and true negative.
print("Accuracy:", accuracy)

[[83  4]
 [ 2 48]]
Accuracy: 0.9562043795620438


#SVM Clasification

In [53]:
dataset_class = pd.read_csv("/content/drive/MyDrive/Data_classification_copy.csv") #Pull the Social_Network_Ads.csv file from CSV into a variable.
x_values = dataset_class.iloc[:, :-1].values #Indexing all the values till the last row.
y = dataset_class.iloc[:, -1].values #Indexing all the values till the last column.

In [54]:
from sklearn.model_selection import train_test_split #Importing train_test_split that is a method to split the specified dataset into training set and testing set.
X_train,X_test,y_train,y_test=train_test_split(x_values,y,test_size = 0.20, random_state = 0) #Four subsets are returned. x_values is the data matrix. y is the target variable. X_train and y_train are used for training the model. X_test and y_test are used to evaluate the performance of the given model.

In [55]:
from sklearn.preprocessing import StandardScaler #Importing Standard scaler libraries
sc = StandardScaler() #Creating a standardScaler object that can be used for transforming the given data. StandardScalar is used for rescaling the features for implementing standard normal distribution. 
X_train=sc.fit_transform(X_train) #Implement the fit_transform method to the X_train to fit the scaler on the training data
X_test=sc.transform(X_test) #When implementing, it results in each feature with a mean of 0 and a standard deviation of 1, therefore resulting in better performnace
y = np.ravel(y)

In [56]:
from sklearn.svm import SVC #Importing SVC class from svm classifier.
classifier = SVC(kernel = 'rbf', random_state = 0) #Use the Radial basis function kernel. 
classifier.fit(X_train,y_train) #Fit method helps in training the classifier on the given training data.

SVC(random_state=0)

In [57]:
y_pred = classifier.predict(X_test)

In [58]:
y_pred = classifier.predict(X_test) #Predicting the X_test dataset which is a 2-D array containing independent variables. 
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) #The concatenation helps to concatenate the previously predicted values and actuaal values in the same column and

[[2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 4]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]]


In [59]:
from sklearn.metrics import confusion_matrix,accuracy_score #Importing the confusing matrix and accuracy_score libraries
cm = confusion_matrix(y_test,y_pred) #The confusion matrix forms a table that summarizes the function and performance of the given algorithm of the test values. It successfully depicts true positive,negative and false positive, negative predictions.
print(cm) #Printing confusion matrix
accuracy = accuracy_score(y_test, y_pred) #Accuracy_score function is used for computing the accuracy of the previous classifier by getting accurate predictions and results are only the true positive and true negative.
print("Accuracy:", accuracy)

[[82  5]
 [ 1 49]]
Accuracy: 0.9562043795620438


#Decision Tree Classification

In [60]:
dataset_class = pd.read_csv("/content/drive/MyDrive/Data_classification_copy.csv") #Pull the Position_Salaries_poly-1.csv file from CSV into a variable.
x_values = dataset_class.iloc[:, :-1].values #Indexing all the values till the last row.
y = dataset_class.iloc[:, -1].values #Indexing all the values till the last column.

In [61]:
from sklearn.model_selection import train_test_split #Importing train_test_split that is a method to split the specified dataset into training set and testing set.
X_train,X_test,y_train,y_test=train_test_split(x_values,y,test_size = 0.25, random_state = 0) #Four subsets are returned. x_values is the data matrix. y is the target variable. X_train and y_train are used for training the model. X_test and y_test are used to evaluate the performance of the given model.

In [62]:
from sklearn.preprocessing import StandardScaler #Importing Standard scaler libraries
sc = StandardScaler() #Creating a standardScaler object that can be used for transforming the given data. StandardScalar is used for rescaling the features for implementing standard normal distribution. 
X_train=sc.fit_transform(X_train) #Implement the fit_transform method to the X_train to fit the scaler on the training data
X_test=sc.transform(X_test) #When implementing, it results in each feature with a mean of 0 and a standard deviation of 1, therefore resulting in better performnace.

In [63]:
from sklearn.tree import DecisionTreeClassifier #This libraries creates an instance of the classifier.
classifier = DecisionTreeClassifier(criterion='entropy', random_state=0) #This type of algorithm is used for classification and builds a decision tree model for predicting the class label. Entropy is used for determining the best split.  
classifier.fit(X_train,y_train) #Fitting the X_train and y_train for visualising

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [64]:
y_pred = classifier.predict(X_test) #Predicting the X_test dataset which is a 2-D array containing independent variables. 


In [65]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) #The concatenation helps to concatenate the previously predicted values and actuaal values in the same column and in a single array.

[[2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 4]
 [4 4]
 [4 2]
 [4 4]
 [4 4]
 [2 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 4]
 [2 2]

In [66]:
from sklearn.metrics import confusion_matrix,accuracy_score #Importing the confusing matrix and accuracy_score libraries
cm = confusion_matrix(y_test,y_pred) #The confusion matrix forms a table that summarizes the function and performance of the given algorithm of the test values. It successfully depicts true positive,negative and false positive, negative predictions.
print(cm) #Printing confusion matrix
accuracy = accuracy_score(y_test, y_pred) #Accuracy_score function is used for computing the accuracy of the previous classifier by getting accurate predictions and results are only the true positive and true negative.
print("Accuracy:", accuracy)

[[103   4]
 [  3  61]]
Accuracy: 0.9590643274853801


#Random Forest Classification 

In [67]:
dataset_rfc = pd.read_csv("/content/drive/MyDrive/Data_classification_copy.csv") #Pull the Social_Network_Ads.csv file from CSV into a variable.
x_rfc = dataset_rfc.iloc[:, :-1].values #Indexing all the values till the last row.
y_rfc = dataset_rfc.iloc[:, -1].values #Indexing all the values till the last column.

In [68]:
from sklearn.model_selection import train_test_split #Importing train_test_split that is a method to split the specified dataset into training set and testing set.
X_train,X_test,y_train,y_test=train_test_split(x_rfc,y_rfc,test_size = 0.25, random_state = 0) #Four subsets are returned. x_values is the data matrix. y is the target variable. X_train and y_train are used for training the model. X_test and y_test are used to evaluate the performance of the given model.

In [69]:
from sklearn.preprocessing import StandardScaler #Importing Standard scaler libraries
sc = StandardScaler() #Creating a standardScaler object that can be used for transforming the given data. StandardScalar is used for rescaling the features for implementing standard normal distribution. 
X_train=sc.fit_transform(X_train) #Implement the fit_transform method to the X_train to fit the scaler on the training data
X_test=sc.transform(X_test) #When implementing, it results in each feature with a mean of 0 and a standard deviation of 1, therefore resulting in better performnace.

In [70]:
from sklearn.ensemble import RandomForestClassifier #Importing RandomForestClassifier libraries
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0) #RFC constructs a multitude of decision trees and also combine the attributes for controlling the overfitting.
classifier.fit(X_train,y_train) #Fitting the X_train and y_train for visualising

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [71]:
y_pred = classifier.predict(X_test)

In [72]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) #The concatenation helps to concatenate the previously predicted values and actuaal values in the same column and in a single array.

[[2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 4]
 [4 2]
 [4 4]
 [4 4]
 [2 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 4]
 [2 2]
 [2 2]
 [2 2]
 [2 4]
 [2 2]

In [73]:
from sklearn.metrics import confusion_matrix,accuracy_score #Importing the confusing matrix and accuracy_score libraries
cm = confusion_matrix(y_test,y_pred) #The confusion matrix forms a table that summarizes the function and performance of the given algorithm of the test values. It successfully depicts true positive,negative and false positive, negative predictions.
print(cm) #Printing confusion matrix
accuracy = accuracy_score(y_test, y_pred) #Accuracy_score function is used for computing the accuracy of the previous classifier by getting accurate predictions and results are only the true positive and true negative.
print("Accuracy:", accuracy)

[[102   5]
 [  6  58]]
Accuracy: 0.935672514619883


#KNN

In [74]:
dataset_knn = pd.read_csv("/content/drive/MyDrive/Data_classification_copy.csv") #Pull the Position_Salaries_poly-1.csv file from CSV into a variable.
x_values = dataset_knn.iloc[:, :-1].values #Indexing all the values till the last row.
y = dataset_knn.iloc[:, -1].values #Indexing all the values till the last column.

In [75]:
from sklearn.model_selection import train_test_split #Importing train_test_split that is a method to split the specified dataset into training set and testing set.
X_train,X_test,y_train,y_test=train_test_split(x_values,y,test_size = 0.35, random_state = 0) #Four subsets are returned. x_values is the data matrix. y is the target variable. X_train and y_train are used for training the model. X_test and y_test are used to evaluate the performance of the given model.

In [76]:
from sklearn.preprocessing import StandardScaler #Importing Standard scaler libraries
sc = StandardScaler() #Creating a standardScaler object that can be used for transforming the given data. StandardScalar is used for rescaling the features for implementing standard normal distribution. 
X_train=sc.fit_transform(X_train) #Implement the fit_transform method to the X_train to fit the scaler on the training data
X_test=sc.transform(X_test) #When implementing, it results in each feature with a mean of 0 and a standard deviation of 1, therefore resulting in better performnace.

In [77]:
from sklearn.neighbors import KNeighborsClassifier #Importing the KNN classifier using KNN libraries
classifier = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p = 2) #Set the n_neighbors to 5 for assigning number of nearest neighbors to 5 for including it in the majority. Metric is set to minkowski that is useful for generating distance.
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [78]:
y_pred = classifier.predict(X_test) #Predicting the X_test dataset which is a 2-D array containing independent variables. 
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) #The concatenation helps to concatenate the previously predicted values and actuaal values in the same column and in a single array.

[[2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 4]
 [4 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]

In [79]:
from sklearn.metrics import confusion_matrix,accuracy_score #Importing the confusing matrix and accuracy_score libraries
cm = confusion_matrix(y_test,y_pred) #The confusion matrix forms a table that summarizes the function and performance of the given algorithm of the test values. It successfully depicts true positive,negative and false positive, negative predictions.
print(cm) #Printing confusion matrix
accuracy = accuracy_score(y_test, y_pred) #Accuracy_score function is used for computing the accuracy of the previous classifier by getting accurate predictions and results are only the true positive and true negative.
print("Accuracy:", accuracy)

[[144   6]
 [  6  84]]
Accuracy: 0.95
