#Artificial Neural Network


>Parthiv Desai

>CPCSC 483 - 03



In [1]:
import numpy as np  #Numpy is widely used library for handling number
import matplotlib.pyplot as plt #Provides a library for data visualization for plotting graphs
import pandas as pd  #Used for data manipulation
import tensorflow as tf

In [2]:
tf.__version__ #Initialising TensorFlow

'2.12.0'

In [3]:
dataset = pd.read_csv("/content/drive/MyDrive/Churn_Modelling.csv") #Pull the Data.csv file from CSV into a variable.
X = dataset.iloc[:,3:-1].values #Indexing all the values till the last row.
y = dataset.iloc[:,-1].values #Indexing y values

In [4]:
from sklearn.preprocessing import LabelEncoder #Label encoder helps with the label indicator matrix in multiclass labels.
le = LabelEncoder() #Label encoding the 'Gender' column
X[:,2] = le.fit_transform(X[:,2]) #Fitting and transforming the x variable and changing it to numbers.

In [5]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [6]:
from sklearn.compose import ColumnTransformer #We use Column Transformer for applying all preprocessing and data extraction pipelines.
from sklearn.preprocessing import OneHotEncoder #One hot encoding the "Geography" column
ct = ColumnTransformer(transformers=[('encooder', OneHotEncoder(), [1])], remainder = 'passthrough') #Column Transformer takes in 1 arguements. Second arguement is remainder which is responsible for other columns. 
X = np.array(ct.fit_transform(X)) #Fitting and transforming the X variable for turning every data in terms of numbers.

In [7]:
print(X)  

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [8]:
from sklearn.model_selection import train_test_split #Splitting data into random train and test basically converting the data into a one-liner
X_train,X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)#Assign the test size at 0.2 so 80% of the data will be used for training and 30% will be used for testing.Random state is used for deciding the splitting of a given data by initializing the internal random number 

In [11]:
from sklearn.preprocessing import StandardScaler #Importing Standard scaler libraries
sc = StandardScaler() #Creating a standardScaler object that can be used for transforming the given data. StandardScalar is used for rescaling the features for implementing standard normal distribution. 
X_train = sc.fit_transform(X_train) #Implement the fit_transform method to the X_train to fit the scaler on the training data
X_test = sc.transform(X_test)  #When implementing, it results in each feature with a mean of 0 and a standard deviation of 1, therefore resulting in better performnace


#Part 2 - Building the ANN

In [12]:
ann = tf.keras.models.Sequential() #Initializing the ANN

In [13]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu')) #Adding the input layer and the first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu')) #Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid')) #Adding the output layer, dimension of y is 1(binary), sigmoid allows the probab values if multi softmax

#Part 3 - Training the ANN

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) #Compiling the ANN, opti performance stocstic gredient decent, it updates the weight to reduce the loss between the pred and the real actual loss. we do loss = category_crossentropy

In [17]:
ann.fit(X_train,y_train, batch_size = 32, epochs = 100) #Training the ANN on the Training set batch size comparing it to pred and the real actual epoch. It is done using multiple iterations.

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5992 - accuracy: 0.7268
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4785 - accuracy: 0.7969
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4448 - accuracy: 0.8049
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4327 - accuracy: 0.8080
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4256 - accuracy: 0.8099
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4200 - accuracy: 0.8152
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4145 - accuracy: 0.8210
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4086 - accuracy: 0.8245
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4031 - accuracy: 0.8276
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3978 - accura

#Making the predictions and evaluating the model

In [18]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5) #Predicting the results of a single observation

1/1 [==============================] - 0s 110ms/step
[[False]]


#Predicting the Test set results

In [19]:
y_pred = ann.predict(X_test) #Predicting the test results
y_pred = (y_pred>0.5) #If y_pred is greater than 0.5, we return 1 indicating true and 2 if false.
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


#Making the Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score #Importing the libraries for finding confusion matrix and accuracy score
cm = confusion_matrix(y_test,y_pred) #Finding the confusion matrix
print(cm)  #Printing the confusion matrix
accuracy_score(y_test, y_pred) #Finding and printing the accuracy score

[[1507   88]
 [ 185  220]]


0.8635